* lessons

** Bring your appraiser to the hearing.
JD Norman Industries v. City of Leslie
** Adjust for time
Sullivan v. City of Grosse Pointe Farms

* published decisions

** Magreta v. Ambassador Steel Co., 158 NW 2d 473 - Mich: Supreme Court 1968
We preface our decision here with the recognition that there is no vested right in the continuation of judicial error. If we have been wrong in our interpretation, we are not only free to, but obligated to, correct that error. 

** MICH. PROPERTIES v. Meridian Twp., 817 NW 2d 548 - Mich: Supreme Court 2012
Next, in Toll Northville Limited Partnership v. Northville Township, we address whether the Tax Tribunal has the authority to reduce an unconstitutional increase in the taxable value of property when the erroneous taxable value was not challenged in the year of the increase.[2] We hold that the Tax Tribunal does have the authority to reduce an unconstitutional previous increase in taxable value for purposes of adjusting a taxable value that was timely challenged in a subsequent year. The Tax Tribunal Act[3] sets forth the Tax Tribunal's jurisdiction.[4] Once its jurisdiction is properly invoked, the Tax Tribunal possesses the same powers and duties as those assigned to a March board of review under the GPTA, including the duty to adjust erroneous taxable values to bring the current tax rolls into compliance with the GPTA. Because the Court of Appeals erroneously held that the Tax Tribunal did not have jurisdiction to review taxable values in years not under appeal, we reverse the Court of Appeals' judgment and remand to that Court to consider Northville Township's remaining issues on appeal regarding the Tax Tribunal's valuation of the properties.

** Hanner v. City of Dearborn Heights, Mich: Court of Appeals 2008
"If the City fails to abide by the MTT's judgment and remedy the situation, petitioner could file suit in circuit court seeking equitable relief to enforce the MTT's writ, order, or directive. Wikman v Novi, 413 Mich 617, 648; 322 NW2d 103 (1982). Accordingly, the MTT should have considered petitioner's claim on this ground."
** ACI HOLDINGS, INC. v. TOWNSHIP OF SYLVAN, Mich: Court of Appeals 2008
MTT does not have jurisdiction to hear fraud cases.
** Beacon Enterprises, Inc. v. Department of Treasury, Mich: Court of Appeals 2013
*** re attorney fees and costs
distinguishing between MCL 600.2591(3)(b) which defines a prevailing party as one who wins on the entire record and MCR 2.114 which makes no mention of "entire record".

"Respondent contends that the Tribunal erred in awarding attorney fees because Enterprises was not the "prevailing party." Respondent cites MCL 600.2591(3)(b), which states that "`[p]revailing party' means a party who wins on the entire record." Respondent contends that Enterprises won the argument about jurisdiction but did not win its argument pertaining to the tax assessment. However, even if it could be argued that the summary-disposition actions pertaining to jurisdiction should not be considered a distinct proceeding for purposes of determining the "prevailing party" under MCL 600.2591, the Tribunal simply did not base its decision exclusively on MCL 600.2591. Indeed, the Tribunal discussed MCR 2.114 extensively in reaching its conclusions. This court rule makes no reference to a party who prevails "on the entire record." Respondent's argument, therefore, is without merit.[4]"
** SCHOENECKERS, INC. v. Department of Treasury, Mich: Court of Appeals 2014

discussing costs and 4 justifications for awarding them.
** Kok v. Cascade Charter Tp., 660 NW 2d 389 - Mich: Court of Appeals 2003
The primary issue before this Court is whether, under Const. 1963, art. 9, ยง 3, as amended by Proposal A, and M.C.L. ยง 211.27a(2)(a), respondent was precluded from reappraising the entire property for the 2000 tax year as new construction without regard to the taxable value of the partially completed construction assessed in the 1999 tax year.
* unpublished decisions

** JD NORMAN INDUSTRIES v. CITY OF LESLIE, Mich: Court of Appeals 2015

Court of Appeals upholds TCV of $6,219,900 despite Norman having bought the business for $6,632,250 and only $1,672,000 of the property being in the taxing jurisdiction. 

The Tribunal gave no weight to the sale, distiguishing a business sale vs an asset sale. 

The Court of Appeals approved, saying this was enough for the Tribunal to circumvent Jones & Laughlin and give no weight to the sale. 

The big mistake was made at the hearing. The appraisal was excluded as hearsay because the appraiser was not there to lay the foundation.

** Sullivan v. City of Grosse Pointe Farms, Mich: Court of Appeals 2014

Court of Appeals affirms the MTT's ruling for the City $600,000 TCV, even though Sullivan bought his property for $528,900 the previous March. 

Petitioner did not present evidence of the market change from March to Tax Day. 

Lesson: Adjust for time.

** ALLEMON v. ROSE TOWNSHIP, Mich: Court of Appeals 2014

Petitioner lost attempt to use the purchase price for two properties as the true cash value because: they submitted a higher appraisal, they relied on Craigslist postings.

** Wise v. City of Holland, Mich: Court of Appeals 2016
*** rule

Finally, turning to the MTT's calculation of TCV, we conclude that the MTT's independent determination of TCV, based on a cost approach as supported by a sales approach, was supported by competent, material and substantial evidence. In particular, in Michigan, property is assessed at 50 percent of its TCV. Const 1963, art 9, ยง 3; MCL 211.27a(1). TCV refers to "the usual selling price at the place where the property to which the term is applied is at the time of assessment, being the price that could be obtained for the property at private sale, and not at auction sale . . . or at forced sale." MCL 211.27(1). In other words, TCV is synonymous with "fair market value." WPW Acquisition Co v Troy, 250 Mich App 287, 298; 646 NW2d 487 (2002). A petitioner bears the burden of establishing a property's TCV. MCL 205.737(3). Purchase price may be relevant to determining the value of a property, Profl Plaza, LLC v Detroit, 250 Mich App 473, 476; 647 NW2d 529 (2002); but there is no presumption that purchase price represents the property's TCV, MCL 211.27(6).

Indeed, there is no single statutorily required method for determining TCV. See Great Lakes Div of Nat Steel Corp v Ecorse, 227 Mich App 379, 390; 576 NW2d 667 (1998). Rather, the MTT must "apply its expertise to the facts of a case in order to determine the appropriate method of arriving at the true cash value of property, utilizing an approach that provides the most accurate valuation under the circumstances." Id. at 389. See also Huron Ridge LP v Ypsilanti Twp, 275 Mich App 23, 28; 737 NW2d 187 (2007). The MTT must make its own, independent determination of TCV, and it is free to accept or reject either party's valuations, or to combine the approaches. Great Lakes Div of Nat'l Steel Corp, 227 Mich App at 389-390. Although not mandatory, the three most common approaches to valuation are: the capitalization of income approach, the sales comparison or market approach, and the cost less depreciation approach. Id. at 390.

In this case, respondent presented evidence of an appraisal employing both a cost approach and a sales approach. Using the sales approach, the appraiser determined petitioner's property to have a value of $126,000. Using a cost approach, and accounting for depreciation, the appraiser determined that petitioner's property had a market value of $125,800. In comparison, petitioner's assertion of valuation was supported by the purchase price of the property as testified to by petitioner and a sampling of purportedly comparable properties compiled by petitioner. The MTT conducted an independent review of this evidence and the documents presented, including the appraisal and property record card detailing the property's features. Based on this review, the MTT concluded that respondent's evidence of the cost approach coupled with the sales approach provided a reliable indicator of value. Thus, the MTT adopted the cost approach to arrive at a value of $125,800 as the property's TCV.

*** holding

In arriving at this TCV, the MTT considered the purchase price evidence offered by petitioner, but correctly recognized that this was not presumed to be the property's TCV. See MCL 211.27(6). Further, the MTT reasoned that the purchase price should not be relied upon in this case because there was insufficient evidence regarding the terms of sale or market exposure of the property. In addition, while the hearing referee excluded petitioner's documentary sales evidence, the MTT ultimately considered this evidence in its final opinion and judgment, explaining that petitioner's attempt to provide evidence of comparable sales was unimpressive because, unlike respondent, petitioner provided market data without making necessary adjustments to the comparable properties. In its final opinion and judgment, the Tribunal explained its acceptance of respondent's sales evidence over petitioner's evidence as follows:

Petitioner's sales evidence does not contain adjustments. Rather, it merely lists the features of the subject and the comparable. From this list, it is clear that adjustments would be required for square footage, bathroom count, and attached versus detached garages. In addition, there are many other features of properties not reflected within Petitioner's evidence such as lot size, quality of construction, age, and condition, all of which could substantially affect the valuation if properly adjusted for. On the other hand, Respondent's sales comparison approach properly contains market based adjustments and indicates an adjusted price range from $115,600 to $153,700. The Tribunal finds that the sales used are comparable to the subject requiring relatively low gross adjustments. As such, the Hearing Referee properly found that Respondent's sales comparison approach supported the assessed true cash value.

** QIN v. TOWNSHIP OF WATERFORD, Mich: Court of Appeals 2015

*** Facts

Using a cost-less-depreciation approach, respondent assessed petitioner's residential real property, located in Waterford Township, as having a SEV and TV of $149,800 for tax year 2013. Petitioner contends that the SEV and TV should not have exceeded $106,500, because he purchased the property for $208,000 on November 30, 2012. The March Board of Review affirmed respondent's valuation, and petitioner filed his petition with the Tribunal in July 2013. Respondent answered in September 2013, asserting that the property had a fair market value of $299,600 and a TV of $106,500. At this point, according to petitioner, he thought his appeal had been resolved, as respondent appeared to have accepted his proposed TV. However, petitioner asserted that on November 15, 2013, respondent informed him by letter that the property's TV was $149,800, as originally assessed.

Petitioner asked the Tribunal to adjourn the hearing scheduled for December 3, 2013, on the basis that he would be out of the country at that time. On November 20, 2013, respondent notified the Tribunal that petitioner did not submit his evidence within 21 days before the hearing, and that its answer to the petition incorrectly listed the property's TV and should have listed it as $149,800. The Tribunal denied petitioner's request for an adjournment for lack of good cause shown.

Following the hearing on December 3, 2013, the hearing referee issued a proposed opinion and judgment setting the property's TCV at $299,600, its SEV at $149,800, and its TV at $149,800. The referee found that petitioner purchased the property on or about November 30, 2012, for $208,000, but explained that the purchase price is not an absolute indication of its TCV. The referee also noted that petitioner's statement that he purchased the property "at the highest bid" indicated that the purchase did not occur under normal market conditions. The referee acknowledged that petitioner submitted sales information for homes in the area to the March Board of Review that he had obtained from Zillow.com, but concluded that the properties listed varied in size and sale price and petitioner did not adjust for the differences. [footnote 1: The referee stated that petitioner's Zillow.com sales comparisons varied in size from 1,285 to 3,000 square feet, and set forth selling prices ranging from $85,000 to $350,000.] Conversely, the referee found, that respondent's sales-comparison approach, in which respondent compared three sales of similar property and made certain adjustments, was reliable. The referee further concluded that respondent's answer to petitioner's appeal contained a clerical error to the extent it listed the property's TV as $106,500. The referee stated that this figure was not accurate and that respondent had alerted petitioner to the clerical error.

Petitioner filed an exception to the referee's proposed opinion and judgment, in which he claimed that "further evidence" showed the property had a TCV of $181,904. The additional evidence included a 2012 appraisal of the property indicating a value of $225,000 and several comparison sheets. Petitioner also alleged that the property was assessed as if it had 131 feet of lake frontage when it only has 56 feet. The Tribunal adopted the referee's valuations. The Tribunal declined to consider petitioner's new evidence on the basis that it was untimely, and it noted that petitioner had presented no evidence that the property has 56 feet of lake frontage, as opposed to the 131 feet of lake frontage stated on the property record card. The Tribunal reiterated that the property's purchase price was not necessarily indicative of its market value, especially considering that the sale may not have occurred under normal market conditions. Further, the Tribunal concluded that respondent's cost-less depreciation approach (as utilized in its initial assessment) was supported by the sales comparison analysis, which indicated an adjusted sales-price range between $294,000 and $335,000. Accordingly, the Tribunal ordered that the property had a TCV of $299,600, a SEV of $149,800, and a TV of $149,800 for tax year 2013.

*** Rule

Nevertheless, "[t]he Tax Tribunal is under a duty to apply its expertise to the facts of a case to determine the appropriate method of arriving at the true cash value of property, utilizing an approach that provides the most accurate valuation under the circumstances." Jones & Laughlin Steel Corp v City of Warren, 193 Mich App 348, 353; 483 NW2d 416 (1992). "Regardless of the approach selected, the value determined must represent the usual price for which the subject property would sell," and "[t]he three most common approaches to valuation are the capitalization-of-income approach, the sales-comparison or market approach, and the cost-less-depreciation approach." Id. (citation omitted). "[T]he tribunal is not bound to accept either of the parties' theories of valuation. It may accept one theory and reject the other, it may reject both theories, or it may utilize a combination of both in arriving at its determination." Id. at 356. Further, "[t]he tribunal may not automatically accept a respondent's assessment, but must make its own findings of fact and arrive at a legally supportable true cash value." Id. at 355. "The Tribunal may adopt the assessed valuation on the tax rolls as its independent finding of true cash value when competent and substantial evidence supports doing so, as long as it does not afford the original assessment presumptive validity." Pontiac Country Club v Waterford Twp, 299 Mich App 427, 435-436; 830 NW2d 785 (2013).


***


** VANCO I LLC v. City of Grand Rapids, Mich: Court of Appeals 2014

*** holding
We conclude that the Tribunal did not err when it corrected the name on the petition under the misnomer doctrine. We conclude that the Tribunal properly denied Grand Rapids's motion for summary disposition because it had subject-matter jurisdiction, though it did so for the wrong reason. We also conclude that the Tribunal did not neglect its duty to independently determine the property's true cash value for tax years 2010, 2011, and 2012, and that it used proper standards when making those findings.

** Parry v. GROVELAND TOWNSHIP, Mich: Court of Appeals 2014

*** MCL 211.27(6) issue

Finally, Parry urges reversal because the assessment exceeds the property's TCV by 50 percent. Parry hinges this entire argument on the two prior sales of the property for $1.00, and concludes that any finding that the value increased by 29,000 times in two years establishes, ipso facto, that the Tribunal erred. This argument is doubly flawed.

First, it presupposes that prior sales history is conclusive of TCV. It is not. See MCL 211.27(6) ("the purchase price paid in a transfer of property is not the presumptive true cash value of the property transferred"); Great Lakes Div of Nat'l Steel Corp, 227 Mich App at 405 ("the sales price of a piece of property is not conclusive evidence of true cash value, even when the sale is for the property that is the subject of the assessment"). Second, Parry's claim assumes that the Tribunal was bound to accept his valuation of the property at $1.00 (the only valuation evidence Parry offered), over the Township's conflicting assessment. The fact that the Tribunal implicitly rejected Parry's valuation is not error, however, where its determination of TCV was otherwise supported by the competent, material and substantial evidence noted previously. The Tribunal did not err.
** LANZO CONSTRUCTION v. City of Southfield, Mich: Court of Appeals 2007
MCR 2.114(E) provides the following

If a document is signed in violation of this rule, the court, on the motion of a party or on its own initiative, shall impose upon the person who signed it, a represented party, or both, an appropriate sanction, which may include an order to pay to the other party or parties the amount of the reasonable expenses incurred because of the filing of the document, including reasonable attorney fees. The court may not assess punitive damages.
Because MCR 2.114(E) states that a court "shall impose" sanctions on a party, its counsel, or both, if it finds that MCR 2.114 was violated, a court has no discretion in determining whether sanctions should be imposed. In re Forfeiture of Cash & Gambling Paraphernalia, 203 Mich App 69, 73; 512 NW2d 49 (1993). When MCR 2.114 is violated, the imposition of sanctions is mandatory. Id.; see also Attorney General v Harkins, 257 Mich App 564, 576; 669 NW2d 296 (2003).

Petitioner argues that MCR 2.114 does not apply to proceedings before the Tax Tribunal because the Tribunal has its own provision, TTR 205.1145, regarding the awarding of costs to a prevailing party. The Tax Tribunal Rules "govern the practice and procedure in all cases and proceedings before the tribunal." TTR 205.1111(1). However, "[i]f an applicable entire tribunal rule does not exist, the 1995 Michigan Rules of Court, as amended, . . . shall govern." TTR 205.1111(4); Signature Villas, LLC v Ann Arbor, 269 Mich App 694, 705; 714 NW2d 392 (2006). TTR 205.1145, like MCR 2.625, addresses the awarding of costs to a prevailing party. The purpose of awarding costs is to reimburse the prevailing party the costs it paid during the course of the litigation. Wells v Dep't of Corrections, 447 Mich 415, 419; 523 NW2d 217 (1994). The purpose of imposing sanctions under MCR 2.114, however, is to "deter parties and attorneys from filing documents or asserting claims and defenses that have not been sufficiently investigated and researched or that are intended to serve an improper purpose." FMB-First Michigan Bank v Bailey, 232 Mich App 711, 723; 591 NW2d 676 (1998). Nothing in TTR 205.1145 or any other Tax Tribunal Rule addresses sanctions. Therefore, because no applicable Tax Tribunal Rule exists regarding sanctions, MCR 2.114 applies to proceedings before the Tax Tribunal. TTR 205.1111(4). Accordingly, because the Tax Tribunal found that petitioner's petition and motion for reconsideration were filed in violation of MCR 2.114(D), the Tax Tribunal erred when it failed to sanction petitioner, its counsel, or both. In re Forfeiture of Cash & Gambling Paraphernalia, supra at 73. We reverse the Tax Tribunal's September 10, 2004 order and all subsequent orders denying respondent's request for costs and attorney fees and remand for a hearing to determine an appropriate sanction.
** SCHOENECKERS, INC. v. Department of Treasury, Mich: Court of Appeals 2014
Tax Tribunal Rule (TTR) 145 (2012) (subsequently amended and renumbered TTR 209) provided that the "tribunal may, upon motion or upon its own initiative, allow a prevailing party in a decision or order to request costs." Further, MCL 205.752(1) provides that "[c]osts may be awarded in the discretion of the tribunal." TTR 145 does not provide guidance regarding when costs are appropriate, but we conclude that given the many and serial failures of respondent during the course of this audit, it was not unreasonable for the tribunal to award costs to petitioner. The main question is whether the award of attorney fees as a sanction was authorized and warranted. MCL 205.732(c) provides that the tribunal may grant "other relief or [issue] writs, orders, or directives that it deems necessary or appropriate in the process of disposition of a matter over which it may acquire jurisdiction." However, neither TTR 145 nor MCL 205.752(1) specifically indicates whether attorney fees or other sanctions may be awarded.

MCR 2.625(A)(2) directs that costs for frivolous claims are awarded under MCL 600.2591. That statute provides for awarding "costs and fees," which include "reasonable attorney fees." MCL 600.2591(1)-(2). The intersection of this court rule and statute indicate that the term "costs" may be construed to include attorney fees.

MCR 2.114 reads, in part:

(A) This rule applies to all pleadings, motions, affidavits, and other papers provided for by these rules. See MCR 2.113(A). In this rule, the term "document" refers to all such papers.
 * * *
(D) The signature of an attorney or party, whether or not the party is represented by an attorney, constitutes a certification by the signer that
(1) he or she has read the document;
(2) to the best of his or her knowledge, information, and belief formed after reasonable inquiry, the document is well grounded in fact and is warranted by existing law or a good-faith argument for the extension, modification, or reversal of existing law; and
(3) the document is not interposed for any improper purpose, such as to harass or to cause unnecessary delay or needless increase in the cost of litigation.
(E) If a document is signed in violation of this rule, the court, on the motion of a party or on its own initiative, shall impose upon the person who signed it . . . an appropriate sanction, which may include . . . the reasonable expenses incurred . . ., including reasonable attorney fees. . . .
There is no tribunal rule that mirrors MCR 2.114. However, the rules of the tribunal provide that it may follow any Michigan Court Rule if there is not a tribunal rule on point. We conclude that the tribunal has authority to award attorney fees as a sanction under MCR 2.114.

