* lessons

** Bring your appraiser to the hearing.
JD Norman Industries v. City of Leslie
** Adjust for time
Sullivan v. City of Grosse Pointe Farms

* unpublished decisions

** JD NORMAN INDUSTRIES v. CITY OF LESLIE, Mich: Court of Appeals 2015

Court of Appeals upholds TCV of $6,219,900 despite Norman having bought the business for $6,632,250 and only $1,672,000 of the property being in the taxing jurisdiction. 

The Tribunal gave no weight to the sale, distiguishing a business sale vs an asset sale. 

The Court of Appeals approved, saying this was enough for the Tribunal to circumvent Jones & Laughlin and give no weight to the sale. 

The big mistake was made at the hearing. The appraisal was excluded as hearsay because the appraiser was not there to lay the foundation.

** Sullivan v. City of Grosse Pointe Farms, Mich: Court of Appeals 2014

Court of Appeals affirms the MTT's ruling for the City $600,000 TCV, even though Sullivan bought his property for $528,900 the previous March. 

Petitioner did not present evidence of the market change from March to Tax Day. 

Lesson: Adjust for time.

** ALLEMON v. ROSE TOWNSHIP, Mich: Court of Appeals 2014

Petitioner lost attempt to use the purchase price for two properties as the true cash value because: they submitted a higher appraisal, they relied on Craigslist postings.

